version: "3.8"
services:
  next-app:
    build: .
    container_name: next-app
    env_file:
      - .env.production
    volumes:
      - ./database:/app/database
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", ""]
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - next-app