version: "3.8"
services:
  next-app:
    build: .
    container_name: next-app
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - ./database:/app/database
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: unless-stopped
    expose:
      - "6379"
    command: ["redis-server", "--save", ""]
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./ssl/privkey.pem:/etc/ssl/certs/privkey.pem
    depends_on:
      - next-app